---
- name: Ensure dependencies are installed
  apt:
    name: curl
    state: present
  become: true

- name: Download spotifyd binary
  get_url:
    url: https://github.com/Spotifyd/spotifyd/releases/download/v{{ spotifyd_version }}/spotifyd-{{ os }}-slim.tar.gz
    dest: /tmp/spotifyd.tar.gz
    mode: '0644'
  become: true

- name: Extract binary
  unarchive:
    src: /tmp/spotifyd.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true

- name: Ensure spotifyd is executable
  file:
    path: /usr/local/bin/spotifyd
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install spotifyd systemd service
  copy:
    dest: /etc/systemd/system/spotifyd.service
    content: |
      [Unit]
      Description=Spotifyd daemon
      Documentation=https://github.com/Spotifyd/spotifyd
      Wants=network-online.target sound.target
      After=network-online.target sound.target


      [Service]
      ExecStart=/usr/local/bin/spotifyd \
        --no-daemon \
        --backend {{ spotify_backend }} \
        --device {{ spotify_device }} \
        --volume-controller {{ spotify_volume_controller }} \
        --verbose \
        -d "{{ spotify_device_name }}"
      Restart=always
      User={{ user }}
      Group={{ user }}
      ProtectSystem=full
      ProtectHome=no
      PrivateTmp=false

      [Install]
      WantedBy=multi-user.target
  notify: Restart spotifyd
  become: true
