---
- name: Ensure dependencies are installed
  apt:
    name: curl
    state: present
  become: true

- name: Download spotifyd binary
  get_url:
    url: https://github.com/Spotifyd/spotifyd/releases/download/v{{ 0.4.1 }}/spotifyd-{{ os }}-slim.tar.gz
    dest: /tmp/spotifyd.tar.gz
    mode: '0644'
  become: true

- name: Extract binary
  unarchive:
    src: /tmp/spotifyd.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=1]
  become: true

- name: Ensure spotifyd is executable
  file:
    path: /usr/local/bin/spotifyd
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Install spotifyd systemd service
  copy:
    dest: /etc/systemd/system/spotifyd.service
    content: |
      [Unit]
      Description=Spotifyd daemon
      After=network.target sound.target

      [Service]
      ExecStart=/usr/local/bin/spotifyd --no-daemon
      Restart=always
      User={{ user }}
      Group={{ user }}
      Environment=PATH=/usr/local/bin:/usr/bin:/bin

      [Install]
      WantedBy=multi-user.target
  notify: Restart spotifyd
  become: true
